#
# Convert the html file generated by the Kindler web app to  mobi format
# (using Amazon's kindlegen utility) and then use Gmail to mail it. 
#  
# The script will try to fetch any images it can using `curl` before performing 
# the conversion using kindlegen
#

require 'yaml'
require 'rubygems'
require 'gmail'
require 'hpricot'

root = File.dirname(__FILE__)

html_file = File.join(root,"tmp","kindler.html")

# Fetch Images and make appropriate modifications to HTML if required
doc = open(html_file) {|f|  Hpricot(f) }
(doc/"img").each do |img|
  url = img['src']
  img_file = File.basename(url) + ".jpeg"
  `curl --silent --connect-timeout 60 --max-time 120 --output #{File.join(root,'tmp',img_file)} -O #{url}`
  img['src'] = img_file
end

File.open(html_file,"w") { |f| f.write(doc.to_s) }

# Generate .mobi file from tmp/kindler.html
mobi_file = File.join(root,"tmp","kindler.mobi")
kindlegen = File.join(root,"kindlegen") # location of kindlegen binary
`rm -f #{mobi_file}`
`#{kindlegen} #{html_file} 2>&1 > #{root}/kindlegen.log`

# Send mail via gmail
settings = YAML.load(File.read(File.join(root,".gmail_credentials")))
gmail = Gmail.new(settings["username"], settings["password"])

gmail.deliver do
  to settings["kindle"]
  add_file mobi_file
end

gmail.logout
