#
# Simple script to convert the html file generated by the Kindler web app to 
# .mobi format (using Amazon's kindlegen utility) and then using Gmail to mail
#
require 'yaml'
require 'rubygems'
require 'gmail'

root = File.dirname(__FILE__)

# FIXME Fetch Images and make appropriate modifications to HTML if required

# Generate .mobi file from tmp/kindler.html
mobi_file = File.join(root,"tmp","kindler.mobi")
html_file = File.join(root,"tmp","kindler.html")
kindlegen = File.join(root,"kindlegen")
`rm -f #{mobi_file}`
`#{kindlegen} #{html_file} 2>&1 > #{root}/kindlegen.log`

# Send mail via gmail
settings = YAML.load(File.read(File.join(root,".gmail_credentials")))
gmail = Gmail.new(settings["username"], settings["password"])

gmail.deliver do
  to settings["kindle"]
  add_file mobi_file
end

gmail.logout
